name: Jest Code Coverage Report

on: [pull_request]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: ziishaned/jest-reporter-action@v0.x
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "yarn jest --coverage"
